AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Env:
    Default: staging
    ConstraintDescription: ''
    Type: String
    Description: target Environment name
  ServiceName:
    Type: String
    Description: Service name for service account
    Default: test
  OidcId:
    Type: String
    Description: Oidc ID
    Default: staging-storage-s3
  Namespace:
    Type: String
    Description: Namespace Name
    Default: default
Resources:
  ChildStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        NamespaceC:
          Ref: Namespace
        ServiceNameC:
          Ref: ServiceName
      TemplateURL: https://s3.us-east-1.amazonaws.com/hello1stack23/f2e88901048e05dee16e3cf169bccf60.template
Outputs:
  Name:
    Value: !Ref Namespace